### ISSUE TITLE
Google Sheets source UI problem 

### ISSUE THREAD

**Issue by icychocolate98** [jitsucom/jitsu#1007]
[](url)## Environment

- **Deploy method**: docker-compose.yml
- **Jitsu version**:  for instance `1.44.1`
- **OS**: `KDE Plasma 5` (Linux)

## Description

I am trying to configure Google Sheets source through service account but I cannot setup due to an UI problem ( selector does not show this option in "Authorization Type" field.

## Steps to reproduce

- Setup Jitsu project v.1.44.1 in local with docker-compose.yml
- Select google-sheets source.
- Try to change "Authorization type" from "OAuth" to "Service account".

## Expected behavior

We should be able to select from OAuth or service account in UI.

## Actual behavior

Cannot select service account config.type in UI.

**Comment by icychocolate98** [comment]
Good morning.

I have configured it using OAuth, after setting up all correct, we get an error.
I paste the error for you:

`Error: Error singer --discover: exit status 1. CRITICAL HTTP-error-code: 400 invalid_request: Could not determine client ID from request.
Traceback (most recent call last):
  File "/home/eventnative/data/venv/tap-google-sheets/lib/python3.9/site-packages/tap_google_sheets/client.py", line 111, in raise_for_error
    response.raise_for_status()
  File "/home/eventnative/data/venv/tap-google-sheets/lib/python3.9/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://oauth2.googleapis.com/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/eventnative/data/venv/tap-google-sheets/bin/tap-google-sheets", line 11, in <module>
    load_entry_point('tap-google-sheets==2.0.0', 'console_scripts', 'tap-google-sheets')()
  File "/home/eventnative/data/venv/tap-google-sheets/lib/python3.9/site-packages/singer/utils.py", line 229, in wrapped
    return fnc(*args, **kwargs)
  File "/home/eventnative/data/venv/tap-google-sheets/lib/python3.9/site-packages/tap_google_sheets/__init__.py", line 36, in main
    with GoogleClient(parsed_args.config['client_id'],
  File "/home/eventnative/data/venv/tap-google-sheets/lib/python3.9/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/home/eventnative/data/venv/tap-google-sheets/lib/python3.9/site-packages/tap_google_sheets/client.py", line 163, in __enter__
    self.get_access_token()
  File "/home/eventnative/data/venv/tap-google-sheets/lib/python3.9/site-packages/backoff/_sync.py", line 94, in retry
    ret = target(*args, **kwargs)
  File "/home/eventnative/data/venv/tap-google-sheets/lib/python3.9/site-packages/tap_google_sheets/client.py", line 198, in get_access_token
    raise_for_error(response)
  File "/home/eventnative/data/venv/tap-google-sheets/lib/python3.9/site-packages/tap_google_sheets/client.py", line 128, in raise_for_error
    raise ex(message)
tap_google_sheets.client.GoogleBadRequestError: HTTP-error-code: 400 invalid_request: Could not determine client ID from request.
 (#400)
    at http://localhost:8000/static/js/main~213b07df.6b29e63b.chunk.js:264:2358`

Setup configuration is right because it's working in other tests.

**Comment by absorbb** [comment]
In `beta` image we have replaced Google Sheets source with airbyte version. 
It also supports "Service account" authorization.  
Can you please check it

**Comment by icychocolate98** [comment]
Good morning!Seems to work fine, thank you very much
