### ISSUE TITLE
Rotor Docker container crashes

### ISSUE THREAD

**Issue by viveknair** [jitsucom/jitsu#1076]
I'm following the self-hosted instructions and I'm running into an issue where Rotor keeps crashing saying that `enriched_connections_push` doesn't exist. 

Briefly looking at the code I'm seeing that it's only referenced once (not exactly sure where it's created).

I saw there was some activity here recently from @absorbb. Not sure if that gives enough context to help me debug this.

```
2023-12-31 15:36:52.600Z ERROR [pg-config-store]: Error executing query: 
 select * from enriched_connections_push
  with params: [] 
 error: relation "enriched_connections_push" does not exist
     at Parser.parseErrorMessage (/app/main.js:122831:98)
     at Parser.handlePacket (/app/main.js:122670:29)
     at Parser.parse (/app/main.js:122583:38)
     at Socket.<anonymous> (/app/main.js:122366:42)
     at Socket.emit (node:events:514:28)
     at addChunk (node:internal/streams/readable:545:12)
     at readableAddChunkPushByteMode (node:internal/streams/readable:495:3)
     at Readable.push (node:internal/streams/readable:375:5)
     at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2023-12-31 15:36:52.604Z WARN  [inmem-store]: Failed to initialize store pg-config. Attempting to load from local cache 
 Error: Error executing the query. See query in logs: relation "enriched_connections_push" does not exist
     at newError (/app/main.js:157555:10)
     at _callee2$ (/app/main.js:172740:17)
     at tryCatch (/app/main.js:172627:1387)
     at Generator.<anonymous> (/app/main.js:172627:4219)
     at Generator.throw (/app/main.js:172627:2238)
     at pg_config_store_asyncGeneratorStep (/app/main.js:172628:119)
     at _throw (/app/main.js:172629:322)
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-12-31 15:36:52.606Z WARN  [inmem-store]: Local cache is not configured for pg-config 
2023-12-31 15:36:52.607Z ERROR [rotor]: process.on unhandledRejection 
 Error: Failed to initialize store pg-config. Initial load failed with Error executing the query. See query in logs: relation "enriched_connections_push" does not exist and no local cache found
     at /app/main.js:172556:16
     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2023-12-31 15:36:52.609Z INFO  [rotor]: Process exited with code 1 
```

**Comment by vklimontovich** [comment]
At this moment, Jitsu undergoes a huge refactoring to implement a few performance improvements we need for Jitsu.Cloud, so docker compose can be malfunctioning at the moment. I a week we'll test in internally and fix it if we face any issues

**Comment by viveknair** [comment]
@absorbb fixed a lot of the issues that I ran into. Coordinated with him via Slack.
